# Generated by Django 4.1.3 on 2022-11-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
